{% set name = "pbr" %}
{% set version = "6.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93ea72ce6989eb2eed99d0f75721474f69ad88128afdef5ac377eb797c4bf76b

build:
  number: 0
  preserve_egg_dir: true
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pbr = pbr.cmd.main:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=64.0.0
  run:
    - python
    - setuptools

test:
  imports:
    - pbr
    - pbr.hooks
    - pbr.pbr_json
    - pbr.version
  requires:
    - pip
  commands:
    - pip check
    - pbr --help

about:
  home: https://launchpad.net/pbr
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: PBR is a library that injects some useful and sensible default behaviors into your setuptools run.
  description: |
    PBR is a library that injects some useful and sensible default behaviors into your setuptools run.
    It started off life as the chunks of code that were copied between all of the OpenStack projects.
    Around the time that OpenStack hit 18 different projects each with at least 3 active branches,
    it seemed like a good time to make that code into a proper reusable library.
  doc_url: https://docs.openstack.org/developer/pbr
  dev_url: https://git.openstack.org/cgit/openstack-dev/pbr

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
    - tschoonj
  skip-lints:
    # https://opendev.org/openstack/pbr/src/tag/6.1.1/pbr/util.py#L76
    - python_build_tool_in_run