{% set name = "pbr" %}
{% set version = "2.0.0" %}
{% set checksum = "0ccd2db529afd070df815b1521f01401d43de03941170f8a800e7531faba265d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - pbr = pbr.cmd.main:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pip

test:
  imports:
    - pbr
    - pbr.cmd
    - pbr.hooks

  commands:
    - pbr --help

about:
  home: https://launchpad.net/pbr
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: Python Build Reasonableness
  doc_url: https://docs.openstack.org/developer/pbr/
  dev_url: https://git.openstack.org/cgit/openstack-dev/pbr

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
