travis:
  secure:
    BINSTAR_TOKEN: xrRKBiTcpbPSaKJlrTpd0mzD1JnK9de0Ao1fUE/F2S3th0MjOnchNlyzW7kjWdP4Rij2NPNzw8vq/A99tLPOYBgndwGM3hfyxl6K1SXMnP9VDgE8Liipsdtnr2RrdQloG6VtfVC+5HBIpHipUKYrUEPn+m7/ohBnA7g/1e4+6WS0jwbVAK2PpAZE1tcNCpKFKUs+AaJpYV9FcjYJDgbTFh5lxLM5Nk0oxvXFXRDLoMoWZhipD4KQFV6+/sl6Rf/TS5A7KWYZhuUnHQSoOTkJxUlOUmDhcCEzc9r7ATtEs8vHCdwboG6GkQCo7eaC47QDF9PX6S4h3kwd8g9/fQ4JKJe4f5AKyQo2u1xEjBFYdbM70PTNt4w59PkaeUn//+a29UWIoNVeQT97skFdyqQLGcZxtU9x7HXYp7w47iQJA8TlPG6pkRLiY2gDTp0NGFkvSJuY8SBqXhhspEE2UOauiQO8bqMMYCk8NK/CBtRIjLWkrDHwzDbC0sT1+7uvCD8puky8r3wnQT7bkIO1wHvImQA+MGwF0n0OQnalBAyQnVSRhQiID0IvndqLHZkVqiKVoaSmltuUYxHgZgw/AoDFnclcpkzZTcb35SbcIYKirvddiZo6afjysve7aibpDvU6VlNfJo13vfwmUJTsvYjCzWc6DVFn5+pGjG6uTDMDJl4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
