travis:
  secure:
    BINSTAR_TOKEN: XJWOtUKEsGLzWm42FD8ViHsMNF3hyUpSusbgc+PZfOqzCZak/UWgEkQ6UsRzZWKRNf7lNwP7p7q4EexKv2gso5QxPxOwvdBOZUHGb3SzAEDD6nleyTLjOYu9orderk0E0WvgPFcxYNMhSwvM8Lm1/4PTIEWuNL6VrFb2byouBPrXaTZjPX9nijBB0pOjeptC5nNiaMTzxJn4uIkcimus9apuloSGssKBWQo21Lb9N4YvSuFjoaRqrCWoZQN/KgSBp2CccxSJvwdInkUXrO36MIbULlT8fHPb9xsSAMWnR4Kid/bP2R5aE4fs/3Y5CSB9pdhRYqFcllPsCEAL/J2nF1IzLjo9a/KXZfTcMT4SD2BWjnWWvA4KO9LTOJfd7kEnauNJnTrctdZvxwwDMWSXQsWo+T+kKsjrN5tDY5k8nhgMYJUsSIHYUeG54o4jEOY9HazqLZYiwV7c4hx2KHt1SaG1F5HS63ylCMCqJoYmJTVRSNAlWk0K6tSGrHja4D1gYS/De/Q2aV2k8ZbgREzqHPHVaD3B5lgfqto8axrvXStUesExk84aZvhKG1wtIn6R5t9xjjmczPD9WFwM+DuLSGre5aBr7buEIYLkkLGm6ZkhGwbMTjcbvM6dSQk4v8T02unvPDDd2ubxl/abSLFrye7D1sBuFqmkPdXpK4lqKIs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
